server:
    port: 8081
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        #type: com.alibaba.druid.pool.DruidDataSoursce
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/t_stadium?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: '08100310'
        # 初始化大小，最小，最大
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        filters: stat,wall,slf4j
    thymeleaf:
        cache: false
        mode: LEGACYHTML5
    mvc:
        static-path-pattern: /static/**
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
mybatis:
    type-aliases-package: com.mty.stadium.model
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
# 分页配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
mapper:
    mappers: com.mty.stadium.util.MyMapper
    not-empty: false
    identity: MYSQL

uploadDir: D:\upload\